[[language]]
name = "rust"

[language.config]
checkOnSave = { command = "clippy" }

[[grammar]]
name = "rust"
source = { git = "https://github.com/tree-sitter/tree-sitter-rust", rev = "0431a2c60828731f27491ee9fdefe25e250ce9c9" }